### PR TITLE
fix MISRA:"Literal zero used in pointer context"

### PR DESCRIPTION
**Pull request by ghost**
MISRA C required pointer to zero should be replace with NULL

Signed-off-by: Huihuang Shi <huihuang.shi@intel.com>

### CODE REVIEW

**Comment by junjiemao1** [comment]
Please do not include the rule ID in your commit log.

**Comment by ghost** [comment]
test

**Comment by ghost** [comment]
test

**Comment by ghost** [comment]
test

**Comment by ghost** [comment]
have a try

**Comment by ghost** [comment]
have a try

**Comment by ghost** [comment]
have a try

**Comment by ghost** [comment]
end test

**Comment by ghost** [comment]
end test

**Comment by ghost** [comment]
hello,world

**Comment by ghost** [comment]
filename:/hypervisor/arch/x86/mtrr.c function:update_ept offset:152: reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp filename:/hypervisor/arch/x86/mtrr.c function:update_ept offset:152: reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp

**Comment by ghost** [comment]
filename:/hypervisor/arch/x86/mtrr.c function:update_ept offset:152:<br>reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>filename:/hypervisor/arch/x86/mtrr.c function:update_ept offset:152:<br>reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>

**Comment by ghost** [comment]
### dddd

**Comment by ghost** [comment]
1. dsdasd
2. dasdasd
3. dasdasd

**Comment by ghost** [comment]
1.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>1.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>

**Comment by ghost** [comment]
1.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>1.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>

**Comment by ghost** [comment]
1.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>2.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>

**Comment by ghost** [comment]
1.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation to a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>2.filename:/hypervisor/arch/x86/mtrr.c&nbsp;&nbsp;function:update_ept&nbsp;&nbsp;offset:152:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reason:Casting operation on a pointer. : (void* to unsigned long*): ( uint64_t * ) vm -> arch_vm.nworld_eptp<br><br>

**Pull request closed without merging**
